import { z } from 'zod';
import { DatabaseSync } from 'node:sqlite';
import { Agent, ToolRegistry, Tool, SQLiteMemoryAdapter } from '../src/index';
import { MockLLMProvider } from './mock-provider';

// 1. Define a tool
const addSchema = z.object({
  a: z.number(),
  b: z.number(),
});

const addTool: Tool<typeof addSchema, number> = {
  name: 'add',
  description: 'Add two numbers together',
  schema: addSchema,
  execute: async ({ a, b }) => a + b,
};

const registry = new ToolRegistry();
registry.register(addTool);

// 2. Setup SQLite adapter
const db = new DatabaseSync(':memory:');
const adapter = new SQLiteMemoryAdapter(db);
const sessionId = 'agent_session_123';

const provider = new MockLLMProvider();
const agent = new Agent(registry, provider);

async function main() {
  console.log('--- Running Persistent Agent Example ---');

  // Step A: Load history from DB (should be empty first)
  let history = await adapter.getHistory(sessionId);
  console.log(`Loaded history from DB (Session: ${sessionId}):`, history.length, 'messages.');

  // Step B: Push initial user question and save it
  const userMsg = { role: 'user', content: 'Calcular la suma de 5 y 10' } as const;
  history.push(userMsg);
  await adapter.saveMessage(sessionId, userMsg);
  console.log(`User query saved: "${userMsg.content}"`);

  // Step C: Run agent loop
  const finalHistory = await agent.run(history);

  // Step D: Save only new messages generated by the agent loop
  for (let i = history.length; i < finalHistory.length; i++) {
    await adapter.saveMessage(sessionId, finalHistory[i]);
  }
  console.log('Agent run completed. New turns saved to SQLite database.');

  // Step E: Reload history from DB to verify it persisted correctly
  const reloadedHistory = await adapter.getHistory(sessionId);
  console.log('\n--- Reloaded History from SQLite Database ---');
  reloadedHistory.forEach((msg) => {
    console.log(`[${msg.role.toUpperCase()}]:`, msg.content ?? `[Tool Calls: ${JSON.stringify(msg.tool_calls)}]`);
  });
}

main().catch(console.error);
