/**
 * Represents a tool call requested by the LLM.
 */
export interface ToolCall {
  /** The unique identifier of the tool call */
  id: string;
  /** The type of tool call (currently only 'function') */
  type: 'function';
  /** The function details */
  function: {
    /** The name of the function to execute */
    name: string;
    /** The arguments to pass to the function, as a JSON-encoded string */
    arguments: string;
  };
}

/**
 * Message sent by the user to the assistant.
 */
export interface UserMessage {
  role: 'user';
  /** The text content of the message */
  content: string;
}

/**
 * Message generated by the assistant.
 */
export interface AssistantMessage {
  role: 'assistant';
  /** The text content of the response */
  content?: string | null;
  /** The reasoning or thinking process of the model (e.g. for DeepSeek-R1) */
  thinking?: string | null;
  /** The tool calls requested by the model */
  tool_calls?: ToolCall[];
}

/**
 * System instruction message.
 */
export interface SystemMessage {
  role: 'system';
  /** The instruction content */
  content: string;
}

/**
 * Message containing the execution result of a tool.
 */
export interface ToolMessage {
  role: 'tool';
  /** The ID of the tool call this result corresponds to */
  tool_call_id: string;
  /** The name of the tool that was executed */
  name: string;
  /** The serialized result of the tool execution */
  content: string;
}

/**
 * Union type representing any message in the chat history.
 */
export type ChatMessage = UserMessage | AssistantMessage | SystemMessage | ToolMessage;

/**
 * The standard response returned by an LLM Provider.
 */
export interface LLMResponse {
  /** The message generated by the LLM */
  message: ChatMessage;
  /** The reason why the LLM stopped generating ('stop', 'tool_calls', etc.) */
  finish_reason: 'stop' | 'tool_calls' | string;
}

/**
 * A streamed chunk from the LLM Provider.
 */
export interface LLMStreamChunk {
  /** Incremental content tokens */
  content?: string;
  /** Incremental thinking/reasoning process tokens */
  thinking?: string;
  /** Incremental tool call updates */
  tool_calls_delta?: Array<{
    /** The index of the tool call in the response array */
    index: number;
    /** The ID of the tool call (if available in this chunk) */
    id?: string;
    /** The type of the tool call */
    type?: 'function';
    function?: {
      /** Incremental function name tokens */
      name?: string;
      /** Incremental arguments string tokens */
      arguments?: string;
    };
  }>;
  /** Set when the stream finishes for this turn */
  finish_reason?: 'stop' | 'tool_calls' | string | null;
}

/**
 * Interface that all LLM providers must implement.
 * This is the Port in Clean Architecture / Hexagonal Architecture.
 */
export interface LLMProvider {
  /**
   * Send a list of messages to the LLM and return the response.
   * 
   * @param messages The chat history to send to the LLM.
   * @param options Additional options, such as available tools.
   */
  chat(messages: ChatMessage[], options?: { tools?: any[] }): Promise<LLMResponse>;

  /**
   * Send a list of messages to the LLM and yield streaming chunks.
   * (Optional, but required if the Agent needs to run in streaming mode).
   * 
   * @param messages The chat history to send to the LLM.
   * @param options Additional options, such as available tools.
   */
  chatStream?(
    messages: ChatMessage[],
    options?: { tools?: any[] }
  ): Promise<AsyncIterable<LLMStreamChunk>> | AsyncIterable<LLMStreamChunk>;
}
